language: php

php:
  - 5.5

cache:
  directories:
    - ~/.composer/cache

sudo: false

install:
  - export COMPOSER_ROOT_VERSION=1.1.x-dev
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: d5fb6d6e99bfc811e1483d163543ebc510d881bd24f9c32012a09ede028983fa

after_script:
  - ./bin/test-reporter
