parameters:
    open_orchestra_bbcode.definition.factory.class : OpenOrchestra\BBcodeBundle\Definition\BBcodeDefinitionFactory
    open_orchestra_bbcode.bbcode_definition.class : OpenOrchestra\BBcodeBundle\Definition\BBcodeDefinition
    open_orchestra_bbcode.parser.class : OpenOrchestra\BBcodeBundle\Parser\BBcodeParser

services:
    open_orchestra_bbcode.definition.factory:
        class: '%open_orchestra_bbcode.definition.factory.class%'
        arguments:
            - '%open_orchestra_bbcode.bbcode_definition.class%'

    open_orchestra_bbcode.parser:
        class: '%open_orchestra_bbcode.parser.class%'
        arguments:
            - '@open_orchestra_bbcode.definition.factory'
